SALES_QUERY = """
    SELECT 
        SUBSTR(BS_DATE(SALES_DATE), 1, 7) AS BS_YEAR_MONTH, 
        SUM(NVL(QUANTITY * NET_GROSS_RATE, 0)) AS SALES_VALUE
    FROM SA_SALES_INVOICE
    WHERE DELETED_FLAG = 'N' 
    AND COMPANY_CODE IN ('06', '0')   
    GROUP BY SUBSTR(BS_DATE(SALES_DATE), 1, 7)
    ORDER BY 1
"""



BRAND_SALES_QUERY = """
SELECT 
    SUBSTR(BS_DATE(A.SALES_DATE), 1, 7) AS BS_YEAR_MONTH,
    NVL(e.brand_name, 'undefined') AS BRAND_NAME,
    SUM(NVL(A.QUANTITY * A.NET_GROSS_RATE, 0)) AS SALES_VALUE
FROM 
    SA_SALES_INVOICE A
    INNER JOIN IP_ITEM_MASTER_SETUP D
        ON A.COMPANY_CODE = D.COMPANY_CODE 
        AND A.ITEM_CODE = D.ITEM_CODE
    LEFT OUTER JOIN 
        (SELECT item_code AS cod, brand_name 
         FROM IP_ITEM_SPEC_SETUP 
         WHERE COMPANY_CODE IN ('06', '0')) e
        ON D.ITEM_CODE = e.cod
WHERE 
    A.DELETED_FLAG = 'N'
    AND A.COMPANY_CODE IN ('06', '0')
GROUP BY 
    SUBSTR(BS_DATE(A.SALES_DATE), 1, 7),
    e.brand_name
ORDER BY 
    BS_YEAR_MONTH, 
    BRAND_NAME
"""