SALES_QUERY = """
    SELECT 
        SUBSTR(BS_DATE(SALES_DATE), 1, 7) AS BS_YEAR_MONTH, 
        SUM(NVL(QUANTITY * NET_GROSS_RATE, 0)) AS SALES_VALUE
    FROM SA_SALES_INVOICE
    WHERE DELETED_FLAG = 'N' 
    AND COMPANY_CODE IN ('06', '0')   
    GROUP BY SUBSTR(BS_DATE(SALES_DATE), 1, 7)
    ORDER BY 1
"""